### ISSUE TITLE
Wrong Emotions Detecting

### ISSUE THREAD

**Issue by kunalgupta777** [rionaldichandraseta/facifier#4]
I tried the code on my machine, and it's giving wrong emotional labels for almost every situation. If I am smiling, it will show me sad or angry etc.

**Comment by chandraseta** [comment]
When you are using the webcam mode, make sure that you are looking straight at the camera for best results. The training data is taken from [KDEF dataset](http://www.emotionlab.se/kdef/) but I only use photos where the person is looking straight at the camera.

**Comment by kunalgupta777** [comment]
I was looking straight into the camera. Tried to change the lighting as well. Also, I checked the image mode, and still, it wrongly labeled a happy face as a neutral one.

**Comment by chandraseta** [comment]
You can try to add more data to training example. The model sometimes gives me wrong result too because training data is mostly white or Caucasian people. Here is an article about [racial bias in facial recognition](https://medium.com/@ODSC/the-impact-of-racial-bias-in-facial-recognition-software-36f37113604c)

**Comment by chandraseta** [comment]
Closed due to inactivity
