### ISSUE TITLE
Not able to read model file!

### ISSUE THREAD

**Issue by AbhinavKoul** [rionaldichandraseta/facifier#5]
In line 70
`   fisher_face_emotion = cv2.face.FisherFaceRecognizer_create()
    fisher_face_emotion.read('E:/GitHub/facifier/src/models/emotion_classifier_model_windows.xml')`

I am getting an error as follows:
`e:/GitHub/facifier/src/facifier.py
Traceback (most recent call last):
  File "e:/GitHub/facifier/src/facifier.py", line 70, in <module>
    fisher_face_emotion.read('E:/GitHub/facifier/src/models/emotion_classifier_model_windows.xml')        
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6lylwdcz\opencv\modules\core\src\persistence.cpp:2089: error: (-215:Assertion failed) isMap() in fu\src\persistence.cpp:2089: error: (-215:Assertion failed) isMap() in function 'cv::FileNode::operator []' `

How to fix this?

Specifications
1. Python 3.7.6 conda
2. OpenCV(4.4.0)

**Comment by chandraseta** [comment]
I searched this error and found the same issue reported in opencv (https://github.com/opencv/opencv/issues/14908)
Their solution is to retrain the model and it could load.

I'm guessing it's caused by newer version of OpenCV that removes the isMap() function.
Try downgrading to older versions of OpenCV such as 3.4.4 or 2.4.13.6

**Comment by AbhinavKoul** [comment]
I tried with OpenCV 3.4.4, it still gave the same error, will retrain and get back with new update

**Comment by AbhinavKoul** [comment]
It worked!
